#!/bin/bash
#SBATCH --job-name=hw11
#SBATCH --output=hw11op.%j.out # %j expands to slurm JobID
#SBATCH --nodes=1
#SBATCH --tasks-per-node=20
#SBATCH --partition=datasci
#SBATCH --gres=gpu:1

#purge and load the correct modules
module purge > /dev/null 2>&1
module load cuda
module load python/3.8
module load intel/19.1.0.166


python train.py fake_or_real_news.csv hw11model > f1
python test.py hw11model predictwords > f2
python test.py fake_or_real_news.csv hw11model predictwords > f3
